#!/bin/sh
# filename:		beep
#
#    Copyright (c) 2013 - 2017 Andreas Schmidhuber <info@a3s.at>
#    All rights reserved.
#
#    Redistribution and use in source and binary forms, with or without
#    modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice, this
#       list of conditions and the following disclaimer.
#    2. Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
#    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# author:		Andreas Schmidhuber
# purpose:		provide different beeps for scripts
# usage:		beep [ NW_FAILED | USER_LOGGED_IN | FSCK_FINISHED | tones ]
# version:	date:		description:
#   0.5     2015.11.24  N: beep on CPU and ZFS ERROR
#	0.4		2015.04.16	C: get extension variables from CONFIG2 instead of reading from config.xml
#	0.3		2014.05.29	C: initial version for Extended GUI (check enabled/disabled)
#	0.2		2012.11.24	N: FSCK_FINISHED and optimizations
# 	0.1					initial version
#------------- initialize variables ------------
cd `dirname $0`
. CONFIG
SPEAKER="/dev/speaker"
CTRL_FILE_CPU="${PREFIX}cpu.alarm"
CTRL_FILE_ZFS="${PREFIX}zfs.alarm"
# from FreNAS: echo O3L30cO4L30cO5L30cO5L30g > $SPEAKER
# from FreNAS: echo O5L30gO5L30cO4L30cO3L30c > $SPEAKER
#-----------------------------------------------

CPU_ERROR ()
{
    touch $CTRL_FILE_CPU
    while [ -e $CTRL_FILE_CPU ]; do echo L8cPL8cL8cPL8cL8cPL8cL8cPL8cL8cPL8c > $SPEAKER; sleep 2; done
}

ZFS_ERROR ()
{
    touch $CTRL_FILE_ZFS
    while [ -e $CTRL_FILE_ZFS ]; do echo L8aPL8aL8aPL8aL8aPL8aL8aPL8aL8aPL8a > $SPEAKER; sleep 5; done
}

NW_FAILED ()
( while true; do echo L4afgL1cP4L4cgaL1f > $SPEAKER; sleep 2; done )

USER_LOGGED_IN ()
( echo g1O3L30cO4L30c > $SPEAKER )

FSCK_FINISHED ()
( echo L4afgL1cP4L4cgaL1f > $SPEAKER; sleep 2; echo O3L30cO4L30c > $SPEAKER; sleep 2;
echo L4afgL1cP4L4cgaL1f > $SPEAKER; sleep 2; echo O3L30cO4L30c > $SPEAKER; sleep 2;
echo L4afgL1cP4L4cgaL1f > $SPEAKER; sleep 2; echo O3L30cO4L30c > $SPEAKER;
)

if [ $RUN_BEEP -eq 0 ]; then exit; fi

case "$1" in
    CPU_ERROR)      CPU_ERROR;;
    ZFS_ERROR)      ZFS_ERROR;;
	FSCK_FINISHED)	FSCK_FINISHED;;
	USER_LOGGED_IN)	USER_LOGGED_IN;;
	NW_FAILED) 		NW_FAILED;;
	*)				echo "$1" > $SPEAKER;
esac
