#!/bin/sh
# filename:		CONFIG
#
#    Copyright (c) 2013 - 2017 Andreas Schmidhuber <info@a3s.at>
#    All rights reserved.
#
#    Redistribution and use in source and binary forms, with or without
#    modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice, this
#       list of conditions and the following disclaimer.
#    2. Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
#
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
#    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
#    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
#    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
#    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
#    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# author:		Andreas Schmidhuber
# purpose:		INITIAL VARIABLES FOR NAS-SCRIPTS
# usage:		. /path/to/CONFIG -> call in every shell script at the first line
# version:	date:		description:
#	4.0		2017.06.15	N: introduced Telegram as new notification service
#	3.3		2017.05.28	N: keep LOCK_SCRIPT quiet if it is called without info message
#	3.2		2015.11.16	C: logger reports now to system log
#	3.1		2015.05.12	C: path for CONFIG2 for other scripts which are not in $SYSTEM_SCRIPT_DIR 
#	3.0		2015.04.09	C: for Extended GUI version 0.5 
#	2.0		2014.04.07	C: for Extended GUI
#	1.1		2013.08.19	N: use $HOST instead of `uname -n`
#	1.0		2013.08.11	N: include IP data
# 	0.2		2013.05.01	N: LOG_DATE
# 	0.1		2013.04.09	initial version
#------------- initialize variables ------------
# change variables to fit for the used system
LOG_DIR="/mnt/DATA/log"					# to save system logs (for embedded systems)
#SYSTEM_LOG_DIR="${clogdir}"    --> obsolete with v3.0 - comes from CONFIG2
SYSTEM_SCRIPT_DIR="/var/scripts"
SCRIPT_BACKUP_DIR="/mnt/DATA/_scripts"
#-----------------------------------------------

################################################
# do NOT change the rest of the config file
################################################
SCRIPT_NAME=`basename $0`
PID=$$
if [ -e $SYSTEM_SCRIPT_DIR/CONFIG2 ]; then
. $SYSTEM_SCRIPT_DIR/CONFIG2            # created by extended-gui_start
fi
LOCK_DIR="/tmp"                         # for script based locks
LOCK_FILE=$LOCK_DIR/$SCRIPT_NAME.lock
LOG_MSG_NOTIFY=$SYSTEM_LOG_DIR/notifications.log
PREFIX="${LOCK_DIR}/extended-gui_"
DT_STR="%Y.%m.%d %H:%M:%S"
LOG_DATE=`date +"%Y.%m.%d_%H-%M"`
HOST=`uname -n`
XML_CONFIG_FILE=/conf/config.xml
#-----------------------------------------------


TELEGRAM ()
{
    /var/scripts/telegram-notify --html --title "$HOST" --text "${SCRIPT_NAME}:%0A${@}"
}

NOTIFY ()
{
	echo "`date +"$DT_STR"` $SCRIPT_NAME $@" >> $LOG_MSG_NOTIFY
	if [ "$1" == "ERROR" ]; then logger "$@"; fi
}

LOCK_SCRIPT ()
{
	if [ -e $LOCK_FILE ]; then
		ps acx | grep -f $LOCK_FILE
		if [ $? -eq 0 ]; then 
            if [ $# -ne 0 ]; then NOTIFY "$1"; fi
            exit 1; 
		else NOTIFY "INFO Remove obsolete pid file for pid `cat $LOCK_FILE`, new pid: ${PID}"; rm -f $LOCK_FILE; fi
	fi
	echo ${PID} > $LOCK_FILE
}

UNLOCK_SCRIPT ()
{ rm -f $LOCK_FILE; }
